// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxRRTMFwt1JXLGSHWTLSUpJqj8Cv6hk28',
    appId: '1:898053547745:web:91c747256a0321b0c0b9a0',
    messagingSenderId: '898053547745',
    projectId: 'flutterbooks-5a938',
    authDomain: 'flutterbooks-5a938.firebaseapp.com',
    storageBucket: 'flutterbooks-5a938.firebasestorage.app',
    measurementId: 'G-B17L124S65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhp-JKj8Ab3VKOgSYDlpFAw9ko-T7ucw',
    appId: '1:898053547745:android:663393b22fd68cd8c0b9a0',
    messagingSenderId: '898053547745',
    projectId: 'flutterbooks-5a938',
    storageBucket: 'flutterbooks-5a938.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGg5mFSXVtY0BPojqS1UkZb1Jo3XGNC3E',
    appId: '1:898053547745:ios:62d02b75725faaa2c0b9a0',
    messagingSenderId: '898053547745',
    projectId: 'flutterbooks-5a938',
    storageBucket: 'flutterbooks-5a938.firebasestorage.app',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGg5mFSXVtY0BPojqS1UkZb1Jo3XGNC3E',
    appId: '1:898053547745:ios:62d02b75725faaa2c0b9a0',
    messagingSenderId: '898053547745',
    projectId: 'flutterbooks-5a938',
    storageBucket: 'flutterbooks-5a938.firebasestorage.app',
    iosBundleId: 'com.example.booksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxRRTMFwt1JXLGSHWTLSUpJqj8Cv6hk28',
    appId: '1:898053547745:web:b6553e9529be9c95c0b9a0',
    messagingSenderId: '898053547745',
    projectId: 'flutterbooks-5a938',
    authDomain: 'flutterbooks-5a938.firebaseapp.com',
    storageBucket: 'flutterbooks-5a938.firebasestorage.app',
    measurementId: 'G-GYQ1VXEXL9',
  );

}